### ISSUE TITLE
Is there any way to set the order of your BitBar icons in menu?

### ISSUE THREAD

**Issue by zverhope** [matryer/bitbar#468] opened 2018-04-30 17:40 UTC
Hi all,

My question is basically the above: I have 5 or 6 BitBar icons running at any one time and their order is changing, which I think happens based on their respective refresh rates. Is there any way to give their position relative to each other in the menu bar a permanent order? I've read all of the documentation I can find and can't see any way of setting this.

Thanks in advance for any help!

**Comment by ipatch** [comment] 2018-05-10 21:18
@zverhope I'd think you'd have to dive into a macOS API call to lock down menu bar icons, as this isn't really a bitbar issue per se.  I can't help but think there is a _defaults write_ somewhere that can handle what you'r looking for.

In the meantime, you can always <kbd>⌘</kbd> click on the icon and change it's position.

cheers 🍻
Chris

**Comment by scottrbaxter** [comment] 2019-08-08 15:40
Unfortunately this doesn't seem to work, at least in Mojave. I can cmd-click and reorder them just as any other icon in the menubar... but they reorder randomly, sleep/wake, quit/relaunch app, etc. yes the manual refresh does also reorder them.

Hacky solution, but the only way I could seem to make them stay in the order I want is `Open Plugin Folder...` in the menu, and rename the files alphanumerically.
e.g.
![image](https://user-images.githubusercontent.com/4142806/62716982-a8e9c080-b9c8-11e9-9dd8-984018cda052.png)

So far this is working, but not an ideal solution.

**Comment by ipatch** [comment] 2019-08-08 15:47
@scottrbaxter 	

how do the numbers correspond to the menubar placement?

ie. if it is prefixed with **1-...** if that the furthest left item on the menubar?

**Comment by scottrbaxter** [comment] 2019-08-08 16:03
@ipatch it seems to be the opposite... prefixed with `1-` will be the furthest to the right. The highest number will be to the left of lower numbers.

**Comment by ipatch** [comment] 2019-08-08 16:12
@scottrbaxter

interesting, so `1-` will appear furthest to the **right**

How does come into play if there are default macOS / Apple menubar icons in the menubar, ie. the wifi pizza menu icon?

Does it put the bitbar icons to the right of all the Apple / macOS icons or does it place the bitbar icons after all the stock macOS icons have been loaded?

**Comment by sohocoke** [comment] 2019-08-08 16:18
https://github.com/matryer/bitbar/pull/502 is the PR that fixes the frequent loss of custom order set by user using cmd-drag. 

None of the PR's since a few years ago seem to be merged into master, however, so you can check out and build from my fork from which the PR was created: https://github.com/bigbearlabs/bitbar

**Comment by scottrbaxter** [comment] 2019-08-08 16:22
@ipatch that's actually a good point, i had bitbar to the left of all other system/3rd party icons. moving them around, when i hit the manual refresh within bitbar, it moved the bitbar plugins to the left of all other apps (right where i had them, initially), in the `[prefixed number]-item` order as stated above.

thanks, @sohocoke, I'll take a look.

**Comment by gingerbeardman** [comment] 2019-08-08 16:25
What happens when one refreshes on its down? does it maintain its place in the order?

**Comment by garyking** [comment] 2019-08-08 16:26
Renaming the plugins to order them has been mentioned before, but whenever I try it, it doesn't work. I still don't know what actually dictates the order of my plugins. I've got about 15 plugins, so if they were in any particularly obvious order, I should notice (like if ordered alphabetically).

**Comment by ipatch** [comment] 2019-08-08 16:37
> Renaming the plugins to order them has been mentioned before, but whenever I try it, it doesn't work. I still don't know what actually dictates the order of my plugins.

![magic](http://images.rapgenius.com/4ghh18ly585egc2k8a2gcad4e.400x300x1.jpg)

**Comment by scottrbaxter** [comment] 2019-08-08 17:39
@garyking I was only able to reorder using numbers, not alpha charterers.

**Comment by garyking** [comment] 2019-08-08 18:22
> @garyking I was only able to reorder using numbers, not alpha charterers.

I've tried that but it didn't work for me.

**Comment by gingerbeardman** [comment] 2019-08-08 18:23
@scottrbaxter could you post some screenshots or video to help? Otherwise I'm considering closing this as we've been here before and it was not resolved. Thanks!

**Comment by ipatch** [comment] 2019-08-08 18:52
@gingerbeardman 

why would you close the issue if hasn't been resolved? IMHO I would keep the issue open so people searching for information on this topic can easily find information about it, instead digging through a closed issue that was never resolved.

**Comment by gingerbeardman** [comment] 2019-08-08 18:53
Dupe https://github.com/matryer/bitbar/issues/416

**Comment by ipatch** [comment] 2019-08-08 18:54
I don't suppose github provides a way to migrate the discussion that happened in this thread to #416 ?

**Comment by gingerbeardman** [comment] 2019-08-08 18:58
@ipatch I just want to try to prevent this issue from becoming a source of misinformation. Hence me asking for proof. 

If there is no proof that this hack works by then I will close the issue to prevent it spreading misinformation and wasting peoples time. 

If there is proof (I would love to see it) then the thread will remain open as a source of information.

**Comment by scottrbaxter** [comment] 2019-08-08 18:58
i would not consider the hacky/manual renaming of the downloaded script(s) a solution to this. it does work seem to work, but i haven't extensively tested it, and don't know to what extent of edge cases that will still be problematic. this feels like a feature request that needs a programatic solution... e.g. proper list of filenames in this folder, that can be indexed and managed within the preferences.

what i've got seems to be working for me, but i can't promise that it'll scale. i've also got a very basic use case compared to some. that said, i'd be in favor of continuing this issue in #416, as this is definitely a dupe.

**Comment by scottrbaxter** [comment] 2019-08-08 19:23
I don't have time to make a video, but here's a few examples of the reordering if this helps.
Downloaded scripts, prior to renaming (seemingly alphabetic order):
<img width="327" alt="1-downloaded-scripts-default-order" src="https://user-images.githubusercontent.com/4142806/62730387-7ac6a980-b9e5-11e9-985f-49531fd10ea8.png">
Renamed, sequentially (1, 2: lower number to the left, just as @ipatch mentioned [here](https://github.com/matryer/bitbar/issues/468#issuecomment-519575523))
<img width="326" alt="2-reordered-1-2-working" src="https://user-images.githubusercontent.com/4142806/62730391-7dc19a00-b9e5-11e9-9454-a915b67faa82.png">
Renamed, using alphabetical characters (a, b: lower character to the right)
<img width="326" alt="3-reordered-a-b-not-working" src="https://user-images.githubusercontent.com/4142806/62730393-7dc19a00-b9e5-11e9-822c-24fae380ce2b.png">
Renamed, using larger numbers (5, 30: lower number to the right)
<img width="326" alt="4-reordered-5-300-working" src="https://user-images.githubusercontent.com/4142806/62730394-7e5a3080-b9e5-11e9-80a4-1f5eaf317216.png">
Renamed, using number and letter (number item is to the right)
<img width="318" alt="5-reordered-100-a" src="https://user-images.githubusercontent.com/4142806/62730977-bf067980-b9e6-11e9-9c89-67e35bd19fd6.png">

It seems that renaming each file to a number value, increasing the starting number will be re-ordered from left to right (1, 2, 3)... this seemed to be the opposite for me earlier though I don't know why.. I cannot reproduce that now. Does this help @gingerbeardman?

**Comment by gingerbeardman** [comment] 2019-08-09 00:04
If other people can confirm?

**Comment by zverhope** [comment] 2019-08-09 03:07
> If other people can confirm?

I can confirm that @scottrbaxter's method is working on my end (running Mojave). Strangely, however, it orders them from right to left (starting from 1) on my machine. Thanks all!

**Comment by adamkdean** [comment] 2019-08-13 10:08
It doesn't work in the latest version of macOS, unfortunately.

**Comment by scottrbaxter** [comment] 2019-08-13 16:31
> It doesn't work in the latest version of macOS, unfortunately.

Could you please verify which macOS version you consider "latest"? I'm on 10.14.6 (macOS Mojave), which is the latest stable version of macOS.

**Comment by joakim** [comment] 2019-08-31 17:56
I can confirm that it works on my MacOS Mojave 10.14.6, and for me it's left-to-right (lowest number = leftmost item).

**Comment by joakim** [comment] 2019-09-01 17:29
Well, after adding a few more plugins the hack no longer held up. I can change the order of some of the plugins, but not all of them. It seems like whether it uses an icon or outputs only text plays a part. Text-only items always stay to the left of icon items on my menubar.

**Comment by sjurgis** [comment] 2020-03-27 01:35
Numbers hack doesn't work completely for me. I've got 6 items and 4th one ended up and the very end, while others are sorted correctly.

**Comment by gingerbeardman** [comment] 2020-03-27 09:21
Yeah, the numbers hack does not work. You need to use a version of BitBar with a code change in. See #502

**Closed** 2020-03-27 09:21 UTC

**Comment by ko5tas** [comment] 2020-04-17 16:26
what seemed to work for me in BitBar v1.9.2:
("-999" is the first one from left, "1" is the first one from right) 
```
$ ls -1 
-999-ip-flag.2m.rb
1-transferwise-currency-tracker.1m_EUR.py
11-transferwise-currency-tracker.1m_USD.py
22_brew-updates.1h.sh
33-arp-spoof-detector.sh
44-clipboard-history.3s.sh
```

![image](https://user-images.githubusercontent.com/1811083/79590965-ca5e8880-80cf-11ea-94e5-5d6394020d46.png)

hope this contributes to making some sense of the way they are sorted...

**Comment by gingerbeardman** [comment] 2020-04-17 18:34
> what seemed to work for me in BitBar v1.9.2:
> ("-999" is the first one from left, "1" is the first one from right)

This has been proven not to work over time.

**Comment by nash8114** [comment] 2020-11-02 10:03
On macOS 10.15.7 the trick with renaming does not work as expected. The order of the items in the top bar appears to be unrelated to the file name, but rather determined by inode number (right-most being the lowest inode). Every time I've refreshed the bitbar, scripts are displayed in inode order.

The inconsistent results (working for some people but not for others) can be explained by people using either symlinks or script files directly. When renaming a regular file, it does not get a new inode number. When renaming a symlink, a new inode is created.

A consistent way to set the order (tested with scripts that all have the same refresh rate) is to make symlinks to the script files in the correct order. Rightmost item symlink should be created first. If you prefer to use script files directly without linking, then use cp to copy each file in the correct order. Use `ls -1i | sort -n` to check whether the order is correct.

**Comment by gingerbeardman** [comment] 2020-11-02 11:10
> On macOS 10.15.7 the trick with renaming does not work as expected.

It's never worked as expected. 

Thanks for your workaround/solution!
