### ISSUE TITLE
Refresh is not cleaning out previous version of script?

### ISSUE THREAD

**Issue by JaredVogt** [matryer/bitbar#195] opened 2016-01-25 20:19 UTC
Not exactly sure what is going on, but here are the symptoms. It seems bitbar runs hot on "Avg Energy Impact," so I created a [quick and dirty plugin](https://gist.github.com/fad4d265b9992e7d663e) to watch the cpu level. The plugin writes out cpu value from top every 3 secs to a /tmp file - and then displays the contents of the file with tail. Correct behavior would be a new entry every 3 secs. When I select refresh from the menu, it will now write two entries every 3 secs... hit refresh again, now you get three entries, and so on. Somehow "refresh" is not clearing out the "old" plugin - it is still running in the background. 
Expected (last 4 entries)
![image](https://cloud.githubusercontent.com/assets/968047/12562731/8d632390-c35b-11e5-991f-d3b1b8076e4c.png)

After 3x refresh (last 4 entries)
![image](https://cloud.githubusercontent.com/assets/968047/12562763/b5e0671a-c35b-11e5-9e87-d49c5ed29285.png)

On refresh, it is leaving "something" behind.

BTW, [excellent article](https://blog.mozilla.org/nnethercote/2015/08/26/what-does-the-os-x-activity-monitors-energy-impact-actually-measure/) on app resource usage.

**Comment by matryer** [comment] 2016-01-25 20:59
This is an excellent bug report. Thanks so much. Will look into this ASAP.
On 25 January 2016 at 20:19:26, Jared Vogt (notifications@github.com) wrote:

Not exactly sure what is going on, but here are the symptoms. It seems bitbar runs hot on "Avg Energy Impact," so I created a quick and dirty plugin to watch the cpu level. The plugin writes out cpu value from top every 3 secs to a /tmp file - and then displays the contents of the file with tail. Correct behavior would be a new entry every 3 secs. When I select refresh from the menu, it will now write two entries every 3 secs... hit refresh again, now you get three entries, and so on. Somehow "refresh" is not clearing out the "old" plugin - it is still running in the background.
Expected (last 4 entries)


After 3x refresh (last 4 entries)


On refresh, it is leaving "something" behind.

BTW, excellent article on app resource usage.

**Comment by eripa** [comment] 2016-02-02 15:45
I've also seen this issue a couple of times. Usually it happens when I hack on a plugin and manually refreshing BitBar multiple times, sometimes the processes gets left behind doing it's thing multiple times in the background (as in the initial report).

Get back to me if I can help out with debugging etc.

**Comment by notTHEwoz** [comment] 2016-02-03 13:12
I see this problem frequently (since v1.3) and have added a line to appended timestamps to a file when my plugin (bash script) is called. It's likely that a refresh does not clear out the old timing. Quitting BB and rerunning seems to fix it until the next refresh. (version 1.4).  I haven't tried 1.5b1 yet, but if it now resets plugins after a wake then it could cause the problem to get worse.

**Comment by matryer** [comment] 2016-02-03 13:13
Definitely would appreciate some help tracking down this bug if anyone has some time?

**Comment by notTHEwoz** [comment] 2016-03-07 14:11
Running 1.6 for a while now and can confirm the problem is still there (extra executions being called on reset and on wake from sleep). During one 24 h period I had 1570 executions for a script that should be called every 5 mins (288 max in 24h). Seems to have gotten worse with the reset after wake. Quitting and rerunning bitbar resumes normal behaviour.
IMHO this is becoming a serious issue. Would like to help try to track down if I had the expertise.

I would think that issues #209 and #263 are related to this one.

**Comment by matryer** [comment] 2016-03-07 15:29
This is now top priority.

**Comment by eripa** [comment] 2016-03-08 05:08
@matryer could you give us some pointers on how to gather debug info?

**Comment by tresni** [comment] 2016-03-08 17:12
Looks like the issue is that releasing _plugins is not calling dealloc on the actual Plugin objects.  I added a dealloc to the ExecutablePlugin class with just a debug message.  It never gets called.
```objc
 - (void) dealloc {
  NSLog(@"Dealloc called");
}
```

So I went a step further.  In the `reset` function I put
```objc
    NSLog(@"Retain count for plugin %@ is %ld", plugin, CFGetRetainCount((__bridge CFTypeRef)_plugins));
...
  NSLog(@"Retain count is %ld", CFGetRetainCount((__bridge CFTypeRef)_plugins));
```

Now this should return "Retain count for plugin XXX is 1" if things are setup correctly.  Unsurprisingly, the actual output I got was:

```
2016-03-08 10:10:07.120 BitBar[48501:17510932] Retain count for plugin <ExecutablePlugin: 0x610000102760> is 2
2016-03-08 10:10:07.124 BitBar[48501:17510932] Retain count for plugin <ExecutablePlugin: 0x6080001005a0> is 2
2016-03-08 10:10:07.130 BitBar[48501:17510932] Retain count for plugin <ExecutablePlugin: 0x610000102e20> is 2
2016-03-08 10:10:07.133 BitBar[48501:17510932] Retain count for plugin <ExecutablePlugin: 0x610000103210> is 2
2016-03-08 10:10:07.135 BitBar[48501:17510932] Retain count for plugin <ExecutablePlugin: 0x618000100480> is 2
2016-03-08 10:10:07.135 BitBar[48501:17510932] Retain count for plugins is 1
```

So the answer appears to be that there are 2 references to plugin and we are only releasing one of them.  Now to figure out where that's happening...

**Comment by tresni** [comment] 2016-03-08 17:30
So actually looks like I may have been on the right track.  Reference count for individual plugins tends to be 2 or 3 when calling `reset`:

```
2016-03-08 10:24:29.090 BitBar[60191:17584526] Retain count [Starting] for plugin <ExecutablePlugin: 0x608000103690> is 1
2016-03-08 10:24:29.090 BitBar[60191:17584526] Retain count [ArrayAdd] for plugin <ExecutablePlugin: 0x608000103690> is 2
2016-03-08 10:24:29.090 BitBar[60191:17584526] Retain count [ nill'd ] for plugin <ExecutablePlugin: 0x608000103690> is 2
2016-03-08 10:24:29.147 BitBar[60191:17584526] Retain count [Starting] for plugin <ExecutablePlugin: 0x608000100a20> is 1
2016-03-08 10:24:29.147 BitBar[60191:17584526] Retain count [ArrayAdd] for plugin <ExecutablePlugin: 0x608000100a20> is 2
2016-03-08 10:24:29.147 BitBar[60191:17584526] Retain count [ nill'd ] for plugin <ExecutablePlugin: 0x608000100a20> is 2
2016-03-08 10:24:29.210 BitBar[60191:17584526] Retain count [Starting] for plugin <ExecutablePlugin: 0x608000103a80> is 1
2016-03-08 10:24:29.210 BitBar[60191:17584526] Retain count [ArrayAdd] for plugin <ExecutablePlugin: 0x608000103a80> is 2
2016-03-08 10:24:29.210 BitBar[60191:17584526] Retain count [ nill'd ] for plugin <ExecutablePlugin: 0x608000103a80> is 2
2016-03-08 10:24:29.280 BitBar[60191:17584526] Retain count [Starting] for plugin <ExecutablePlugin: 0x610000101dd0> is 1
2016-03-08 10:24:29.280 BitBar[60191:17584526] Retain count [ArrayAdd] for plugin <ExecutablePlugin: 0x610000101dd0> is 2
2016-03-08 10:24:29.280 BitBar[60191:17584526] Retain count [ nill'd ] for plugin <ExecutablePlugin: 0x610000101dd0> is 2
2016-03-08 10:24:29.343 BitBar[60191:17584526] Retain count [Starting] for plugin <ExecutablePlugin: 0x610000102010> is 1
2016-03-08 10:24:29.343 BitBar[60191:17584526] Retain count [ArrayAdd] for plugin <ExecutablePlugin: 0x610000102010> is 2
2016-03-08 10:24:29.344 BitBar[60191:17584526] Retain count [ nill'd ] for plugin <ExecutablePlugin: 0x610000102010> is 2
2016-03-08 10:24:38.029 BitBar[60191:17584526] Retain count [ Reset  ] for plugin <ExecutablePlugin: 0x608000103690> is 3
2016-03-08 10:24:38.032 BitBar[60191:17584526] Retain count [ Reset  ] for plugin <ExecutablePlugin: 0x608000100a20> is 3
2016-03-08 10:24:38.035 BitBar[60191:17584526] Retain count [ Reset  ] for plugin <ExecutablePlugin: 0x608000103a80> is 2
2016-03-08 10:24:38.038 BitBar[60191:17584526] Retain count [ Reset  ] for plugin <ExecutablePlugin: 0x610000101dd0> is 2
2016-03-08 10:24:38.041 BitBar[60191:17584526] Retain count [ Reset  ] for plugin <ExecutablePlugin: 0x610000102010> is 3
2016-03-08 10:24:38.102 BitBar[60191:17584526] Retain count [Starting] for plugin <ExecutablePlugin: 0x618000101290> is 1
2016-03-08 10:24:38.102 BitBar[60191:17584526] Retain count [ArrayAdd] for plugin <ExecutablePlugin: 0x618000101290> is 2
2016-03-08 10:24:38.102 BitBar[60191:17584526] Retain count [ nill'd ] for plugin <ExecutablePlugin: 0x618000101290> is 2
2016-03-08 10:24:38.162 BitBar[60191:17584526] Retain count [Starting] for plugin <ExecutablePlugin: 0x610000103060> is 1
2016-03-08 10:24:38.162 BitBar[60191:17584526] Retain count [ArrayAdd] for plugin <ExecutablePlugin: 0x610000103060> is 2
2016-03-08 10:24:38.162 BitBar[60191:17584526] Retain count [ nill'd ] for plugin <ExecutablePlugin: 0x610000103060> is 2
2016-03-08 10:24:38.222 BitBar[60191:17584526] Retain count [Starting] for plugin <ExecutablePlugin: 0x6180001001b0> is 1
2016-03-08 10:24:38.222 BitBar[60191:17584526] Retain count [ArrayAdd] for plugin <ExecutablePlugin: 0x6180001001b0> is 2
2016-03-08 10:24:38.222 BitBar[60191:17584526] Retain count [ nill'd ] for plugin <ExecutablePlugin: 0x6180001001b0> is 2
2016-03-08 10:24:38.282 BitBar[60191:17584526] Retain count [Starting] for plugin <ExecutablePlugin: 0x608000104770> is 1
2016-03-08 10:24:38.282 BitBar[60191:17584526] Retain count [ArrayAdd] for plugin <ExecutablePlugin: 0x608000104770> is 2
2016-03-08 10:24:38.282 BitBar[60191:17584526] Retain count [ nill'd ] for plugin <ExecutablePlugin: 0x608000104770> is 2
2016-03-08 10:24:38.341 BitBar[60191:17584526] Retain count [Starting] for plugin <ExecutablePlugin: 0x6100001017a0> is 1
2016-03-08 10:24:38.341 BitBar[60191:17584526] Retain count [ArrayAdd] for plugin <ExecutablePlugin: 0x6100001017a0> is 2
2016-03-08 10:24:38.341 BitBar[60191:17584526] Retain count [ nill'd ] for plugin <ExecutablePlugin: 0x6100001017a0> is 2
```

Pretty sure retain count should be 2 on the ExecutablePlugin (one for `plugins`, one for the `for` loop.)  So sometimes it appears to be off by one, but that doesn't explain why dealloc *never* gets called..  Anyway, that's as far as I got.

**Comment by matryer** [comment] 2016-03-08 18:25
… interesting… I might get @iosdeveloper to look at this :)

Thanks for the digging

**Comment by naddeoa** [comment] 2016-03-11 07:48
Looking through the comments, their dates and the commits, a few seemed like they could be suspect:

https://github.com/matryer/bitbar/commit/c2ea4e439725d8951f9aebcc8f63dc5fb7717dfe
https://github.com/matryer/bitbar/commit/d95c7e77db4ce358694c973f38232a767ba787de

I wanted to try to revert them and test, but I can't seem to get the project building. I've never done any sort of Mac development, so I'm probably just missing some steps. Trying to run `make` from the command line after cloning gives me failures with messages like:

```
no such file or directory:  '/Users/naddeo/workspace/bitbar/App/Vendor/AHProxySettings/AHProxySettings/AHProxy.m'.
```

Do you have any links I can follow to obvious things, or any documentation written for bitbar specific setup? I'm using BitBar to call an API that throttles, so this kind of bug is a real bummer.

**Comment by iosdeveloper** [comment] 2016-03-11 08:34
@naddeoa Did you run `git submodule init && git submodule update` as per the README? Why don't you open the Xcode project and build from there?

**Comment by naddeoa** [comment] 2016-03-13 01:00
Thanks @iosdeveloper, that was much easier. Getting it setup in xcode let me browse the code base a little. I created a pull request with a potential fix. This is literally the first objective c I have ever written, so don't feel free change it if it isn't up to snuff, no hard feelings.

I confirmed that extra Plugins were created every time refresh is used. I also suspect the implementation of dispatch_async and the NSTimers inside of it, but I don't know objective c well enough to say anything definitive yet.

Instead of trying to correctly delete plugins when users hit refresh, my changes stops deleting plugins entirely and just calls their refresh method instead. One side effect is that BitBar has to be restarted before it will pick up new plugins, but the state around Plugins looks like its getting kind of complicated.

https://github.com/matryer/bitbar/pull/274

**Comment by naddeoa** [comment] 2016-03-14 04:09
OK, I guess that fix breaks loading plugins over the url scheme. My take-two is below:

https://github.com/matryer/bitbar/pull/276

This fix will have plugins assert that they are in the `PluginManager`'s `_plugins` before scheduling any additional tasks. Looking at the memory graph in xcode, it looks like this solve the leak as well, though it is a little hacky (I'm not sure if it should be the plugin's job to do that).

If that does work, then I would strongly suspect the implementation of the `Plugin.refresh`. I'm not sure how `dispatch_async` works entirely, but it seems plausible that if plugins are executing `dispatch_async` which executes `Plugin.refresh` which executes `dispatch_async` (etc.) that something might be holding onto the plugin reference. It effectively executes forever as far as I can see.

**Comment by tresni** [comment] 2016-03-14 04:29
I think @naddeoa  hit the nail on the head with `dispatch_async` and `self`.  I remember seeing something about that when trying to follow this stuff down the rabbit hole, but initially it didn't make sense.  

The call to `self` within the [code block](https://github.com/matryer/bitbar/blob/2ada38cec739abaa214c379b7d05054fa015771a/App/BitBar/ExecutablePlugin.m#L80) **does** keep a reference to the plugin object.  The "solution" would normally be a `weak` reference.  However, just making it a `weak` reference assigned to `self` won't work as then `self` could dealloc anytime within the block.  Apparently the solution is to cast a `weak` reference outside the block and then within the block do a `strong` assignment to the `weak` reference.  This makes sure that once the block is actually called that the Plugin object is guarenteed to stay around, but if it's just waiting around it can be safely deallocated.  (This is what I understand and I haven't tested this.)

Example stolen from http://www.logicsector.com/ios/avoiding-objc-retain-cycles-with-weakself-and-strongself-the-easy-way/
```
__weak typeof(self) weakSelf = self;
    dispatch_async(dispatch_get_main_queue(), ^{
        [weakSelf doThis];
        [weakSelf doThat];
        [Manager.sharedInstance updateSuccessCount];
    });
```

Google "dispatch_async self retain cycle" for more details, but that definitely looks like the culprit.

**Comment by naddeoa** [comment] 2016-03-14 05:12
That makes a lot of sense @tresni. When I tried to test it, xcode claimed that `__weak` isn't supported in my current target. I wasn't sure  if it was a config thing on my end or if bitbar is trying to target older operating systems. Searching online, people claimed that `__unsafe_unretained` is an almost equal substitute. During tests, it seems to also fix the issue.

https://github.com/matryer/bitbar/pull/277

Feel free to change that around or replace it with `__weak` if that was just a noob mistake, but that solution feels better to me than having plugins interact with the plugin manager more than they already do. Who's managing who anyways.

**Comment by tresni** [comment] 2016-03-14 05:16
No `unsafe_unretained` appears to be correct if you are targeting OSX 10.6.  From what I can find 10.7 implements weak references.  Was just compiling everything myself, glad to see it worked for you :)  Will post my results as soon as I have them.

**Comment by tresni** [comment] 2016-03-14 06:12
Yeah since target is 10.6 you have to use unsafe_unretained. Once target is changed to 10.7 or later I think we can move to weak. 

Looking at your PR though you need to be careful. Accessing the weak reference directly could lead to a state where the weak reference has become nil and crash. Hence why the example does a cast to a strong reference.  Not sure how that will work with the double dispatch_async but something to play with. (Also figure out why there are 2 dispatch events)

-- Brian

**Comment by iosdeveloper** [comment] 2016-03-14 06:37
@naddeoa @tresni Really appreciate your work on this! The first dispatch executes the script on a background thread, the second dispatch updates the UI on the main thread.

**Comment by tresni** [comment] 2016-03-14 08:35
I think I finally got it..  There were a couple of other retain cycles:

* `PluginManager` -> `Plugin` -> `PluginManager`  
  I made the reference from `Plugin` -> `PluginManager` weak
* `Plugin` -> `NSTimer` -> `Plugin`  
  Even with the weak reference, this still caused issues (check Google, it's everywhere!)  The solution was to implement `- (void) close` that tells the `ExecutablePlugin` to invalidate all it's timers.

So far, this seems to be working for me and the sample plugin **never** produces multiple outputs and reference count always cleans up.

My only concern: the sample code I pasted seems to indicate we should be casting the weak reference to a strong reference inside of the dispatch_async blocks to prevent it from de-allocating inside the block.  Probably wouldn't hurt anything to do that, but I haven't tested yet.  So far, I haven't had any issues.  PR coming shortly.

**Comment by tresni** [comment] 2016-03-14 08:54
That PR includes the strong reference.  It didn't create any new issues in my testing.

**Comment by naddeoa** [comment] 2016-03-14 17:51
Man, objective c.... (pun intended)

I'm considering updating the unit tests to assert that plugin's are deallocated as well when a `PluginManager`'s `_plugins` is set to `nil`. 

Do you know when the next release of bitbar will be? I'd like to go back to using the cask version if I can.

**Closed** 2016-03-14 20:10 UTC

**Comment by notTHEwoz** [comment] 2016-03-15 07:24
I'm now running 1.8.0 and the problem seems to be fixed for me too. Well done all.

**Comment by naddeoa** [comment] 2016-03-15 20:06
Just a note for people who develop on BitBar or install BitBar via `brew cask`. I updated BitBar and noticed that older versions of it were showing up in spotlight, which I mistakenly launched, making me think this fix didn't work.

If you have extra versions of BitBar around and spotlight keeps picking them up, either add some exclude dirs to spotlight in the system settings, or hold command whlie in spotlight to find where that extra version is (laucnhing with command+enter in spotlight will open it in finder). In my case, brew orphaned version 1.6 and I had to `rm` it. Spotlight also picks up builds that you do in xcode it seems...

**Comment by matryer** [comment] 2016-03-15 22:57
Does the cask update automatically? Or does someone need to do a PR?

**Comment by tresni** [comment] 2016-03-15 23:51
PR but looks like @iosdeveloper already [got it covered](https://github.com/caskroom/homebrew-cask/blob/master/Casks/bitbar.rb)

**Comment by naddeoa** [comment] 2016-03-15 23:58
Well, I'm definitely on 1.8 through cask. I'm on a phone right now so I
can't check easily, but I suspect someone already updated cask.
