### ISSUE TITLE
Bitbar duplicating menu items.

### ISSUE THREAD

**Issue by aarinsmith** [matryer/bitbar#100] opened 2016-01-06 01:20 UTC
![image](https://cloud.githubusercontent.com/assets/5971758/12132336/bb9b6790-b3cf-11e5-8c46-1904e4c134f2.png)

![image](https://cloud.githubusercontent.com/assets/5971758/12132353/e13c3b64-b3cf-11e5-9f6e-e02eb2f6d724.png)

Tried a small example for multi line in bit bar:
```
#!/bin/bash
echo "1" 
echo "2" 
echo "3" 
echo "---" 
echo "menu"
```

The numbers cycle however on each loop when it reaches 3 the menu item is duplicated. Now that I have removed the script from the plugins folder it removed a single item but three remain. Not sure what has caused this. I am running OSX 10.11.1

**Comment by matryer** [comment] 2016-01-06 02:16
What version of BitBar?

**Comment by matryer** [comment] 2016-01-06 12:38
Duplicate of https://github.com/matryer/bitbar/issues/21

**Closed by matryer** 2016-01-06 12:38 UTC
