### ISSUE TITLE
BitBar 1.10.1 does no longer execute shell scripts

### ISSUE THREAD

**Issue by faxotherapy** [matryer/bitbar#603] opened 2021-01-05 11:20 UTC
After updating from 1.9.2 to 1.10.1, my shell scripts are no longer executed.

Here's the content of `HTTPS_Port_Status.1m.sh` that I put in `/usr/local/etc/BitBar/` directory:
```shell
#!/bin/bash

if [[ "8118" = $(networksetup -getsecurewebproxy "Thunderbolt Ethernet" | grep -Eo "[0-9]{4}") ]]
  then
  echo "🔒 TLS | color=red"; echo "---"; echo "Filter encrypted requests… | color=green bash=/Users/$USER/bin/PORTS2PROX.sh"
else
  echo -e "\b"
fi
```

Content of `PORTS2PROX.sh` file:
```shell
#!/bin/bash
sudo networksetup -setwebproxy       "Thunderbolt Ethernet" 127.0.0.1 8118
sudo networksetup -setsecurewebproxy "Thunderbolt Ethernet" 127.0.0.1 8079
exit 0
```

BitBar 1.9.2 was able to execute my scripts. I thus reverted back to 1.9.2.

**Comment by austinbutler** [comment] 2021-01-09 21:53
Possible duplicate of https://github.com/matryer/bitbar/issues/596.

**Comment by matryer** [comment] 2021-01-27 10:16
Closing, as it's a duplicate.

**Closed by matryer** 2021-01-27 10:16 UTC
