### ISSUE TITLE
Ability to sort plugins

### ISSUE THREAD

**Issue by JayBrown** [matryer/bitbar#341] opened 2016-06-14 14:33 UTC
This might become irrelevant if move/rearrange functionality is available (see [#158](https://github.com/matryer/bitbar/issues/158)), but maybe there's a quick and easy way to sort plugins, so they appear in a certain order in the menu bar, whether together as a bunch or (in a later version) separated. I know, it's easy to do by simply renaming the basenames, but sometimes (e.g. with plugin distributions to other users/customers) this is not an option. Therefore my suggestion to add an option (a window) in Preferences, which shows a list of the active plugins, and where the user can just rearrange the order by dragging them up/down the list.

**Comment by iosdeveloper** [comment] 2016-06-19 08:18
I wonder how this will work in macOS Sierra: http://9to5mac.com/2016/06/18/macos-sierra-rearrange-third-party-menu-bar-icons/

**Comment by JayBrown** [comment] 2016-06-19 19:06
You already have a similar functionality when you install Bartender. But with the Bartender setup you can only move around BitBar plugins en bloc. (Except for the LittleSnitch Monitor, which is strange.) Maybe Sierra will be more intelligent, and you'll be able to move every BitBar plugin individually… we'll see. :)

**Comment by ffittschen** [comment] 2016-08-28 19:45
Has anyone tried this in the macOS 10.12 beta?

**Comment by fenhl** [comment] 2016-10-26 06:53
It seems to work correctly in Sierra. However, a plugin's position seems to reset if its output is empty.

**Comment by aharris88** [comment] 2016-12-16 17:06
This looks like a duplicate of #158.

**Comment by matthew-groth** [comment] 2017-03-08 22:13
+1
Currently I can reposition my plugins, but only temporarily as they reset their position on refresh.

**Comment by skylartaylor** [comment] 2017-07-28 03:06
So I figured out a workaround to this. If you go to the plugins folder, and prefix the plugin files with a number in the order you want them in reverse order it will follow that order regardless of how many times you refresh or reboot.

For example:
```
1_ColorfulBatteryLevel.5s.sh
2_wifi.15s.sh
3_itunes.10s.sh
4_sonos.3s.sh
```
Hope this helps!

**Comment by fenhl** [comment] 2017-07-28 05:48
This only works if none of your plugins ever disappear. I have several plugins which don't produce any output at all under certain conditions (e.g. no new &lt;insert website here> notifications, or battery level above 70%), and these will be added to the left end of the bar, instead of the expected position, when they generate output for the first time after starting or refreshing BitBar.

**Comment by manuelrego27** [comment] 2018-10-02 16:09
This still doesn't work #sad

**Comment by garyking** [comment] 2019-01-03 20:38
The naming trick doesn't even seem to work for me? Can anyone confirm that it still works for them? Otherwise at the very least, wouldn't the plugins be sorted alphabetically by their filenames, if you don't number them? Which in my case, doesn't seem to be what's happening, anyway.

**Comment by gingerbeardman** [comment] 2020-03-27 09:22
See code change in #502

**Closed by gingerbeardman** 2020-03-27 09:22 UTC
